import "server-only";
import arm from "@/data/stones/arm.json";
import cga from "@/data/stones/cga.json";
import kig from "@/data/stones/kig.json";
import ssd from "@/data/stones/ssd.json";
import syd from "@/data/stones/syd.json";
import type { Stone } from "./stone-vocabulary";

/**
 * Supplier stock lists, generated by scripts/import-stones.py from the
 * suppliers' workbooks — one file per supplier, named by SKU prefix. Don't
 * edit src/data/stones/*.json by hand; re-run the script with the new
 * workbook. A new supplier's file needs an import line here.
 *
 * Origin follows the grading lab: IGI stones are lab-grown, GIA stones
 * natural, except where the workbook states the stone was grown (a few are
 * GIA-graded CVD stones), which the script files as lab-grown.
 *
 * As in real-stones.ts, report numbers, prices and stock locations are not in
 * these files.
 */
export const SUPPLIER_STONES = [...cga, ...kig, ...syd, ...arm, ...ssd] as Stone[];
