import "server-only";
import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { SHAPE_BY_SLUG, type ShapeSlug } from "./shapes";
import type { Stone } from "./stone-vocabulary";

/**
 * Supplier stock lists, generated by scripts/import-stones.py from the
 * suppliers' workbooks — one file per supplier, named by SKU prefix. Don't
 * edit src/data/stones/*.json by hand; re-run the script with the new
 * workbook.
 *
 * Origin follows the grading lab: IGI stones are lab-grown, GIA stones
 * natural, except where the workbook states the stone was grown (a few are
 * GIA-graded CVD stones), which the script files as lab-grown.
 *
 * As in real-stones.ts, report numbers, prices and stock locations are not in
 * these files.
 *
 * The files are read from disk once per server process rather than imported:
 * an import compiles tens of thousands of stones into every server bundle
 * that touches them, several times over, which is what pushed the deployed
 * server past its size limit. next.config.ts traces the folder into the
 * standalone output.
 */

const DIR = path.join(process.cwd(), "src", "data", "stones");

/** Earlier suppliers first, so the catalogue's default order stays put as files are added. */
const ORDER = ["cga", "kig", "syd", "arm", "ssd"];

type Cell = string | number | null;

/** The table layout written by `encode()` in scripts/import-stones.py. */
type StockFile = {
  format: 1;
  fields: string[];
  /** Per field, the distinct words a row refers to by position; -1 means not stated. */
  values: Record<string, string[]>;
  rows: Cell[][];
};

function decode(file: StockFile, name: string): Stone[] {
  if (file.format !== 1) throw new Error(`src/data/stones/${name}: unknown format ${file.format}`);
  const column = Object.fromEntries(file.fields.map((field, i) => [field, i]));
  const text = (row: Cell[], field: string): string | undefined => {
    const cell = row[column[field]];
    const words = file.values[field];
    if (!words) return cell as string;
    return cell === -1 ? undefined : words[cell as number];
  };
  const num = (row: Cell[], field: string) => row[column[field]] as number;

  return file.rows.map((row) => {
    const shape = text(row, "shape") as ShapeSlug;
    const stone = {
      sku: text(row, "sku"),
      shape,
      shapeName: text(row, "shapeName"),
      shapeCode: SHAPE_BY_SLUG[shape].code,
      origin: text(row, "origin"),
      carat: num(row, "carat"),
      color: text(row, "color"),
      clarity: text(row, "clarity"),
      cut: text(row, "cut"),
      polish: text(row, "polish"),
      symmetry: text(row, "symmetry"),
      fluorescence: text(row, "fluorescence"),
      lab: text(row, "lab"),
      measurements: `${text(row, "measurements")} mm`,
      tablePercent: num(row, "tablePercent"),
      depthPercent: num(row, "depthPercent"),
      featured: false,
    } as Stone;
    // Match the hand-kept lists, which leave ungraded fields out entirely.
    if (stone.cut === undefined) delete stone.cut;
    if (stone.fluorescence === undefined) delete stone.fluorescence;
    return stone;
  });
}

function loadSupplierStones(): Stone[] {
  const rank = (name: string) => {
    const i = ORDER.indexOf(name);
    return i === -1 ? ORDER.length : i;
  };
  const names = readdirSync(DIR)
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.slice(0, -".json".length))
    .sort((a, b) => rank(a) - rank(b) || a.localeCompare(b));
  return names.flatMap((name) =>
    decode(JSON.parse(readFileSync(path.join(DIR, `${name}.json`), "utf8")) as StockFile, name),
  );
}

export const SUPPLIER_STONES: Stone[] = loadSupplierStones();
